[package]
name = "ctd-decoder"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow.workspace = true
base64.workspace = true
clap.workspace = true
jsonwebkey.workspace = true
nix.workspace = true
oci-client.workspace = true
ocicrypt-rs.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
walkdir.workspace = true
